In [1]:
import cv2
import numpy as np

In [2]:
#read and show video stream capture Image
#detect face show bonding box
#Flattern the largest face and save into numpy array
#Repeat the above for multiple people to generate training data



# initialise the camera
cap=cv2.VideoCapture(0)

#face detection using harcascade show bonding boxes

face_cascade=cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")

skip=0
#to strore the image in a array

face_data=[]
dataset_path="./data/"

file_name=input("enter your name")




while True:
    ret,frame=cap.read()
    
    
    if ret==False:
        continue
        
     #to conver the frme into gray frame
    gray_frame=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    
    
        
      
    faces=face_cascade.detectMultiScale(frame,1.3,5)    
    #print(faces)
    faces=sorted(faces,key=lambda f:f[2]*f[3])
    
    
      #pick the last face coz last face is having large area
    #drawing rectangle in faces
    #to iterate over the faces
    
    for face in faces[-1:]:
        x,y,w,h=face
        
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        
        
    
    #Exract (Crop requirred area):Region of interest
        offset=10
        face_section=frame[y-offset:y+h+offset,x-offset:x+w+offset]
    #to resise the face data
        face_section=cv2.resize(face_section,(100,100))
    
    
    #to store data on every tenth image
    skip+=1
    if (skip%10==0):
        face_data.append(face_section)
        print(len(face_data))
    
    
  
    
    cv2.imshow("Frame",frame)
    cv2.imshow("face section",face_section)
        
    
    
    
    #store every 10th face
    if(skip%10==0):
        #store the 10th face
        pass
    
    key_pressed=cv2.waitKey(1)&0xFF
    if key_pressed==ord('q'):
        break
        
#conver a facelist into numpy array

face_data=np.asarray(face_data)
print(face_data)
face_data=face_data.reshape((face_data.shape[0],-1))
print(face_data.shape)

#save this data into file system
np.save(dataset_path+file_name+'.npy',face_data)
print("data succesfully stored at"+dataset_path+file_name+'.npy')
        
cap.release()
cv2.destroyAllWindows()


enter your namealok
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
[[[[228 229 230]
   [227 228 229]
   [229 230 231]
   ...
   [184 193 195]
   [185 194 196]
   [185 194 196]]

  [[228 231 231]
   [227 230 230]
   [228 230 230]
   ...
   [185 194 197]
   [187 196 198]
   [188 197 199]]

  [[225 229 229]
   [226 230 230]
   [226 230 230]
   ...
   [187 196 199]
   [187 196 198]
   [186 195 197]]

  ...

  [[198 202 205]
   [198 202 204]
   [199 203 205]
   ...
   [110 119 122]
   [145 154 159]
   [168 177 184]]

  [[196 200 202]
   [199 203 203]
   [201 204 204]
   ...
   [ 90  82  75]
   [ 92  85  81]
   [101  94  92]]

  [[199 202 206]
   [197 201 203]
   [198 202 204]
   ...
   [101  78  66]
   [ 99  76  64]
   [ 96  73  60]]]


 [[[224 228 230]
   [223 225 227]
   [226 228 230]
   ...
   [185 192 193]
   [184 191 193]
   [184 191 193]]

  

In [17]:
print(face_data.shape)

(20, 30000)
